"""
Cash Tracker Module
====================
State machine that tracks per-person cash interactions across video frames.
Detects pickups, deposits, handovers, zone violations, and pocket events.

Architecture:
  - Each tracked person has a CashProfile with a state (NO_CASH / HOLDING_CASH)
  - On each frame, the tracker compares current cash associations vs. previous frame
  - State transitions generate CashEvent objects for logging and alerting

Integration:
  Called from main.py after cash_detector.detect() and associate_with_persons().
"""

from enum import Enum
from dataclasses import dataclass, field
from typing import Optional
import logging

logger = logging.getLogger(__name__)


# ── Enums & Data Classes ──────────────────────────────────────────────

class CashState(Enum):
    """Per-person cash holding state."""
    NO_CASH = "NO_CASH"
    HOLDING_CASH = "HOLDING_CASH"


class CashEventType(Enum):
    """Types of cash events generated by the tracker."""
    CASH_PICKUP = "CASH_PICKUP"           # Cash appeared on person
    CASH_DEPOSIT = "CASH_DEPOSIT"         # Cash deposited at register
    CASH_HANDOVER = "CASH_HANDOVER"       # Cash transferred between people
    CASH_OUTSIDE_ZONE = "CASH_OUTSIDE_ZONE"  # Cash detected outside safe zones
    CASH_POCKET = "CASH_POCKET"           # Cash disappeared outside a register zone (pocketed?)


@dataclass
class CashEvent:
    """A single cash interaction event."""
    event_type: CashEventType
    person_id: int
    timestamp: float         # Current time in seconds
    frame_idx: int
    zone: str                # Zone where event occurred
    confidence: float        # Average confidence of cash detections involved
    partner_id: Optional[int] = None   # For handover events
    bbox_snapshot: Optional[str] = None  # "x1,y1,x2,y2" of cash at event time

    def to_dict(self):
        """Convert to a dictionary for CSV/JSON export."""
        return {
            "event_type": self.event_type.value,
            "person_id": self.person_id,
            "timestamp": round(self.timestamp, 2),
            "frame_idx": self.frame_idx,
            "zone": self.zone,
            "confidence": round(self.confidence, 3),
            "partner_id": self.partner_id,
            "bbox_snapshot": self.bbox_snapshot,
        }

    def __repr__(self):
        partner = f", partner={self.partner_id}" if self.partner_id else ""
        return (f"CashEvent({self.event_type.value}, person={self.person_id}, "
                f"zone={self.zone}, t={self.timestamp:.1f}s{partner})")


@dataclass
class CashProfile:
    """Tracks cash state for a single person across frames."""
    person_id: int
    state: CashState = CashState.NO_CASH
    cash_hold_start_time: float = 0.0
    cash_hold_start_zone: str = "Unknown"
    last_cash_confidence: float = 0.0
    last_cash_bbox: Optional[list] = None
    frames_holding: int = 0
    frames_without_cash: int = 0  # Counter for debouncing


# ── Cash Tracker (State Machine) ──────────────────────────────────────

# Zone types that are considered "safe" for cash handling
SAFE_CASH_ZONES = {"cashier", "cash_register", "money_exchange"}


class CashTracker:
    """
    Tracks per-person cash states across frames and generates events.
    
    State Machine per person:
    
        NO_CASH ──[cash detected near person]──> HOLDING_CASH
            │                                        │
            │  (generates CASH_PICKUP event)         │
            │                                        │
        HOLDING_CASH ──[cash disappears]──> NO_CASH
            │                                    │
            │  At register? → CASH_DEPOSIT       │
            │  Not at register? → CASH_POCKET    │
            │                                    │
        HOLDING_CASH ──[cash moves to other person]──> CASH_HANDOVER
    
    Debouncing:
        - Cash must be detected for N consecutive frames to trigger HOLDING_CASH
        - Cash must be absent for M consecutive frames to trigger deposit/pocket
        - This prevents flickering from detection noise
    """

    def __init__(
        self,
        pickup_debounce=3,     # Frames cash must be seen before triggering pickup
        deposit_debounce=5,    # Frames cash must be absent before triggering deposit
        zone_alert_cooldown=30,  # Frames between repeated zone violation alerts
    ):
        """
        Args:
            pickup_debounce (int): Min consecutive frames with cash before triggering pickup.
            deposit_debounce (int): Min consecutive frames without cash before triggering deposit.
            zone_alert_cooldown (int): Min frames between zone violation alerts for same person.
        """
        self.pickup_debounce = pickup_debounce
        self.deposit_debounce = deposit_debounce
        self.zone_alert_cooldown = zone_alert_cooldown

        # { person_id: CashProfile }
        self._profiles = {}

        # All generated events (accumulated across all frames)
        self._events = []

        # Cooldown tracker for zone alerts { person_id: last_alert_frame }
        self._zone_alert_cooldowns = {}

        # Previous frame's cash holder set (for handover detection)
        self._prev_holders = set()

    def update(self, frame_idx, current_time, person_tracks, cash_associations, roi_manager=None):
        """
        Process one frame of data and generate any cash events.
        
        Args:
            frame_idx (int): Current frame index.
            current_time (float): Current timestamp in seconds.
            person_tracks (dict): {logical_id: {"bbox": [x1,y1,x2,y2], "cls": int}}
            cash_associations (dict): Output from CashDetector.associate_with_persons()
                {"assigned": {person_id: [CashDetection, ...]}, "unassigned": [...]}
            roi_manager: ROIManager instance (optional, for zone lookups).
        
        Returns:
            list[CashEvent]: Events generated this frame (may be empty).
        """
        frame_events = []
        assigned = cash_associations.get("assigned", {})
        current_holders = set(assigned.keys())

        # Ensure all tracked persons have a profile
        for pid in person_tracks:
            if person_tracks[pid]["cls"] == 0 and pid not in self._profiles:
                self._profiles[pid] = CashProfile(person_id=pid)

        # --- Process each person ---
        for pid, profile in self._profiles.items():
            has_cash_now = pid in current_holders

            # Get person's current zone
            zone_name = "Unknown"
            zone_type = None
            if pid in person_tracks and roi_manager and roi_manager.has_zones:
                bbox = person_tracks[pid]["bbox"]
                cx = (bbox[0] + bbox[2]) / 2
                cy = (bbox[1] + bbox[3]) / 2
                zone_name, zone_type = roi_manager.get_zone_with_type(cx, cy)

            # Get average confidence if holding cash
            avg_conf = 0.0
            cash_bbox_str = None
            if has_cash_now and pid in assigned:
                confs = [c.confidence for c in assigned[pid]]
                avg_conf = sum(confs) / len(confs)
                # Use the first detection's bbox as snapshot
                first_bbox = assigned[pid][0].bbox
                cash_bbox_str = f"{int(first_bbox[0])},{int(first_bbox[1])},{int(first_bbox[2])},{int(first_bbox[3])}"

            # --- STATE TRANSITIONS ---

            if profile.state == CashState.NO_CASH:
                if has_cash_now:
                    profile.frames_holding += 1
                    profile.frames_without_cash = 0

                    # Debounce: wait N frames before confirming pickup
                    if profile.frames_holding >= self.pickup_debounce:
                        profile.state = CashState.HOLDING_CASH
                        profile.cash_hold_start_time = current_time
                        profile.cash_hold_start_zone = zone_name
                        profile.last_cash_confidence = avg_conf
                        profile.last_cash_bbox = assigned[pid][0].bbox if pid in assigned else None

                        event = CashEvent(
                            event_type=CashEventType.CASH_PICKUP,
                            person_id=pid,
                            timestamp=current_time,
                            frame_idx=frame_idx,
                            zone=zone_name,
                            confidence=avg_conf,
                            bbox_snapshot=cash_bbox_str,
                        )
                        frame_events.append(event)
                        logger.info(f"  [Cash] {event}")
                else:
                    profile.frames_without_cash += 1
                    # Grace period: allow 2 frames of missing cash before resetting the pickup counter
                    if profile.frames_without_cash > 2:
                        profile.frames_holding = 0

            elif profile.state == CashState.HOLDING_CASH:
                if has_cash_now:
                    # Still holding — update state
                    profile.frames_without_cash = 0
                    profile.last_cash_confidence = avg_conf
                    if pid in assigned:
                        profile.last_cash_bbox = assigned[pid][0].bbox

                    # Check for zone violation (cash outside safe zones)
                    if zone_type and zone_type not in SAFE_CASH_ZONES:
                        last_alert = self._zone_alert_cooldowns.get(pid, -999)
                        if frame_idx - last_alert >= self.zone_alert_cooldown:
                            event = CashEvent(
                                event_type=CashEventType.CASH_OUTSIDE_ZONE,
                                person_id=pid,
                                timestamp=current_time,
                                frame_idx=frame_idx,
                                zone=zone_name,
                                confidence=avg_conf,
                                bbox_snapshot=cash_bbox_str,
                            )
                            frame_events.append(event)
                            self._zone_alert_cooldowns[pid] = frame_idx
                            logger.info(f"  [Cash] {event}")

                else:
                    profile.frames_without_cash += 1

                    # Debounce: wait M frames before confirming deposit/pocket
                    if profile.frames_without_cash >= self.deposit_debounce:
                        # Check if cash went to another person (handover)
                        new_holders = current_holders - self._prev_holders
                        handover_partner = None
                        for new_pid in new_holders:
                            if new_pid != pid:
                                handover_partner = new_pid
                                break

                        if handover_partner is not None:
                            event = CashEvent(
                                event_type=CashEventType.CASH_HANDOVER,
                                person_id=pid,
                                timestamp=current_time,
                                frame_idx=frame_idx,
                                zone=zone_name,
                                confidence=profile.last_cash_confidence,
                                partner_id=handover_partner,
                            )
                        elif zone_type and zone_type in SAFE_CASH_ZONES:
                            # Cash deposited at a register — legitimate
                            event = CashEvent(
                                event_type=CashEventType.CASH_DEPOSIT,
                                person_id=pid,
                                timestamp=current_time,
                                frame_idx=frame_idx,
                                zone=zone_name,
                                confidence=profile.last_cash_confidence,
                            )
                        else:
                            # Cash disappeared outside safe zone — suspicious
                            event = CashEvent(
                                event_type=CashEventType.CASH_POCKET,
                                person_id=pid,
                                timestamp=current_time,
                                frame_idx=frame_idx,
                                zone=zone_name,
                                confidence=profile.last_cash_confidence,
                            )

                        frame_events.append(event)
                        logger.info(f"  [Cash] {event}")

                        # Reset state
                        profile.state = CashState.NO_CASH
                        profile.frames_holding = 0
                        profile.frames_without_cash = 0
                        profile.last_cash_bbox = None

        # Update previous holders for next frame's handover detection
        self._prev_holders = current_holders.copy()

        # Accumulate events
        self._events.extend(frame_events)

        return frame_events

    def get_all_events(self):
        """Return all accumulated cash events."""
        return self._events

    def get_active_cash_holders(self):
        """Return person IDs currently holding cash."""
        return [
            pid for pid, profile in self._profiles.items()
            if profile.state == CashState.HOLDING_CASH
        ]

    def get_person_cash_state(self, person_id):
        """Get cash state for a specific person."""
        if person_id in self._profiles:
            return self._profiles[person_id].state.value
        return CashState.NO_CASH.value

    def get_summary(self):
        """Get a summary dict for debugging/logging."""
        return {
            "total_events": len(self._events),
            "active_holders": len(self.get_active_cash_holders()),
            "events_by_type": {
                etype.value: sum(1 for e in self._events if e.event_type == etype)
                for etype in CashEventType
            },
        }
