"""
Cash Tracker Module (v2 — Zone-Free)
======================================
State machine that tracks per-person cash interactions across video frames.
Detects pickups, deposits, handovers, zone violations, and pocket events.

Architecture:
  - Each tracked person has a CashProfile with a 5-state machine
  - On each frame, the tracker compares current cash associations vs. previous frame
  - State transitions generate CashEvent objects for logging and alerting
  - Works with OR without ROI zones (behavioral fallback)

State Machine:
  NO_CASH → CASH_APPEARING → CASH_CONFIRMED → NO_CASH
                                    │
                               CASH_OCCLUDED (grace period)
                                    │
                               cash_gone() → behavioral decision

Integration:
  Called from module.py after cash_detector.detect() and associate_with_persons().
"""

from enum import Enum
from collections import deque
from dataclasses import dataclass, field
from typing import Optional, Dict, Set, Tuple
import logging

logger = logging.getLogger(__name__)


# ── Enums & Data Classes ──────────────────────────────────────────────

class CashState(Enum):
    """Per-person cash holding state (5-state machine)."""
    NO_CASH = "NO_CASH"
    CASH_APPEARING = "CASH_APPEARING"      # Debouncing: seen cash but not confirmed
    CASH_CONFIRMED = "CASH_CONFIRMED"      # Confirmed cash holder
    CASH_OCCLUDED = "CASH_OCCLUDED"        # Briefly lost detection (grace period)
    SUSPICIOUS = "SUSPICIOUS"              # Cash disappeared + moving away


class CashEventType(Enum):
    """Types of cash events generated by the tracker."""
    CASH_PICKUP = "CASH_PICKUP"                  # Cash appeared on person
    CASH_DEPOSIT = "CASH_DEPOSIT"                # Cash deposited (at register or behaviorally inferred)
    CASH_HANDOVER = "CASH_HANDOVER"              # Cash transferred between people
    CASH_OUTSIDE_ZONE = "CASH_OUTSIDE_ZONE"      # Cash detected outside safe zones (only when zones exist)
    CASH_POCKET = "CASH_POCKET"                  # Cash disappeared suspiciously (requires high confidence)
    NEUTRAL = "NEUTRAL"                          # Cash disappeared, but no alert warranted


@dataclass
class CashEvent:
    """A single cash interaction event."""
    event_type: CashEventType
    person_id: int
    timestamp: float         # Current time in seconds
    frame_idx: int
    zone: str                # Zone where event occurred (or "Unknown")
    confidence: float        # Average confidence of cash detections involved
    partner_id: Optional[int] = None   # For handover events
    bbox_snapshot: Optional[str] = None  # "x1,y1,x2,y2" of cash at event time

    def to_dict(self):
        """Convert to a dictionary for CSV/JSON export."""
        return {
            "event_type": self.event_type.value,
            "person_id": self.person_id,
            "timestamp": round(self.timestamp, 2),
            "frame_idx": self.frame_idx,
            "zone": self.zone,
            "confidence": round(self.confidence, 3),
            "partner_id": self.partner_id,
            "bbox_snapshot": self.bbox_snapshot,
        }

    def __repr__(self):
        partner = f", partner={self.partner_id}" if self.partner_id else ""
        return (f"CashEvent({self.event_type.value}, person={self.person_id}, "
                f"zone={self.zone}, t={self.timestamp:.1f}s{partner})")


@dataclass
class CashProfile:
    """Tracks cash state for a single person across frames."""
    person_id: int
    state: CashState = CashState.NO_CASH
    cash_hold_start_time: float = 0.0
    cash_hold_start_zone: str = "Unknown"
    last_cash_confidence: float = 0.0
    last_cash_bbox: Optional[list] = None
    frames_with_cash: int = 0         # Counter during APPEARING (debounce)
    frames_without_cash: int = 0      # Counter during OCCLUDED (grace)
    suspicious_confirm_count: int = 0  # Frames in SUSPICIOUS state
    last_seen_frame: int = 0          # For stale cleanup
    # Rolling position history for velocity/stationarity
    positions: deque = field(default_factory=lambda: deque(maxlen=60))


# ── Cash Tracker (State Machine) ──────────────────────────────────────

# Zone types that are considered "safe" for cash handling
SAFE_CASH_ZONES = {"cashier", "cash_register", "money_exchange"}


class CashTracker:
    """
    Tracks per-person cash states across frames and generates events.

    5-State Machine per person:

        NO_CASH ──[cash detected]──> CASH_APPEARING
            │                             │
            │                   [debounce: N frames]
            │                             │
        CASH_APPEARING ──[confirmed]──> CASH_CONFIRMED
                                          │
                                    [cash disappears]
                                          │
                                    CASH_OCCLUDED ──[grace window]──> resolve_cash_gone()
                                          │                              │
                                    [cash returns] ←──────── CASH_CONFIRMED
                                                                         │
                                                              resolve() picks one:
                                                                ├─ HANDOVER
                                                                ├─ DEPOSIT (zone or behavioral)
                                                                ├─ SUSPICIOUS → POCKET (if confirmed)
                                                                └─ NEUTRAL (default, no alert)

    Key improvement over v1: Default is NEUTRAL (no alert), not CASH_POCKET.
    """

    def __init__(
        self,
        pickup_debounce=15,           # Frames cash must be seen before confirming
        deposit_debounce=15,          # (Legacy, now handled by occlusion grace)
        zone_alert_cooldown=30,       # Frames between repeated zone violation alerts
        occlusion_grace_frames=20,    # Frames to wait before deciding cash is gone (0.8s at 25fps)
        suspicious_confirm_count=3,   # Frames in SUSPICIOUS before POCKET alert
        stale_profile_frames=300,     # Remove profiles not seen for this many frames (~12s)
        stationary_threshold_px=15,   # Max center movement to be "stationary"
        proximity_threshold_px=200,   # Max distance between two persons for "near"
    ):
        self.pickup_debounce = pickup_debounce
        self.deposit_debounce = deposit_debounce
        self.zone_alert_cooldown = zone_alert_cooldown
        self.occlusion_grace_frames = occlusion_grace_frames
        self.suspicious_confirm_count = suspicious_confirm_count
        self.stale_profile_frames = stale_profile_frames
        self.stationary_threshold_px = stationary_threshold_px
        self.proximity_threshold_px = proximity_threshold_px

        # { person_id: CashProfile }
        self._profiles: Dict[int, CashProfile] = {}

        # All generated events (accumulated across all frames)
        self._events = []

        # Cooldown tracker for zone alerts { person_id: last_alert_frame }
        self._zone_alert_cooldowns = {}

        # Previous frame's cash holder set (for handover detection)
        self._prev_holders: Set[int] = set()

    def update(
        self,
        frame_idx: int,
        current_time: float,
        person_tracks: dict,
        cash_associations: dict,
        roi_manager=None,
        roles: Optional[Dict[int, str]] = None,
    ) -> list:
        """
        Process one frame of data and generate any cash events.

        Args:
            frame_idx: Current frame index.
            current_time: Current timestamp in seconds.
            person_tracks: {logical_id: {"bbox": [x1,y1,x2,y2], "cls": int}}
            cash_associations: Output from CashDetector.associate_with_persons()
            roi_manager: ROIManager instance (optional, for zone lookups).
            roles: {person_id: "Cashier"|"Customer"} (optional, for behavioral decisions).

        Returns:
            list[CashEvent]: Events generated this frame (may be empty).
        """
        frame_events = []
        assigned = cash_associations.get("assigned", {})
        current_holders = set(assigned.keys())
        roles = roles or {}

        # Ensure all tracked persons have a profile
        for pid in person_tracks:
            if person_tracks[pid].get("cls") == 0:
                if pid not in self._profiles:
                    self._profiles[pid] = CashProfile(person_id=pid)
                # Update position history
                bbox = person_tracks[pid].get("bbox", [0, 0, 0, 0])
                cx = (bbox[0] + bbox[2]) / 2
                cy = (bbox[1] + bbox[3]) / 2
                self._profiles[pid].positions.append((cx, cy))
                self._profiles[pid].last_seen_frame = frame_idx

        # --- Process each person ---
        for pid, profile in list(self._profiles.items()):
            has_cash_now = pid in current_holders

            # Get person's current zone
            zone_name = "Unknown"
            zone_type = None
            if pid in person_tracks and roi_manager and roi_manager.has_zones:
                bbox = person_tracks[pid]["bbox"]
                cx = (bbox[0] + bbox[2]) / 2
                cy = (bbox[1] + bbox[3]) / 2
                zone_name, zone_type = roi_manager.get_zone_with_type(cx, cy)

            # Get average confidence if holding cash
            avg_conf = 0.0
            cash_bbox_str = None
            if has_cash_now and pid in assigned:
                confs = [c.confidence for c in assigned[pid]]
                avg_conf = sum(confs) / len(confs)
                first_bbox = assigned[pid][0].bbox
                cash_bbox_str = f"{int(first_bbox[0])},{int(first_bbox[1])},{int(first_bbox[2])},{int(first_bbox[3])}"

            # --- STATE TRANSITIONS ---

            if profile.state == CashState.NO_CASH:
                if has_cash_now:
                    # Start debouncing
                    profile.state = CashState.CASH_APPEARING
                    profile.frames_with_cash = 1
                    profile.frames_without_cash = 0

            elif profile.state == CashState.CASH_APPEARING:
                if has_cash_now:
                    profile.frames_with_cash += 1
                    profile.frames_without_cash = 0

                    # Debounce complete → confirmed
                    if profile.frames_with_cash >= self.pickup_debounce:
                        profile.state = CashState.CASH_CONFIRMED
                        profile.cash_hold_start_time = current_time
                        profile.cash_hold_start_zone = zone_name
                        profile.last_cash_confidence = avg_conf
                        profile.last_cash_bbox = assigned[pid][0].bbox if pid in assigned else None

                        event = CashEvent(
                            event_type=CashEventType.CASH_PICKUP,
                            person_id=pid,
                            timestamp=current_time,
                            frame_idx=frame_idx,
                            zone=zone_name,
                            confidence=avg_conf,
                            bbox_snapshot=cash_bbox_str,
                        )
                        frame_events.append(event)
                        logger.info(f"  [Cash] {event}")
                else:
                    profile.frames_without_cash += 1
                    # Allow brief gaps during debounce (2 frame grace)
                    if profile.frames_without_cash > 2:
                        profile.state = CashState.NO_CASH
                        profile.frames_with_cash = 0
                        profile.frames_without_cash = 0

            elif profile.state == CashState.CASH_CONFIRMED:
                if has_cash_now:
                    # Still holding — update state
                    profile.frames_without_cash = 0
                    profile.last_cash_confidence = avg_conf
                    if pid in assigned:
                        profile.last_cash_bbox = assigned[pid][0].bbox

                    # Zone violation check (only when zones ARE defined)
                    if zone_type and zone_type not in SAFE_CASH_ZONES:
                        last_alert = self._zone_alert_cooldowns.get(pid, -999)
                        if frame_idx - last_alert >= self.zone_alert_cooldown:
                            event = CashEvent(
                                event_type=CashEventType.CASH_OUTSIDE_ZONE,
                                person_id=pid,
                                timestamp=current_time,
                                frame_idx=frame_idx,
                                zone=zone_name,
                                confidence=avg_conf,
                                bbox_snapshot=cash_bbox_str,
                            )
                            frame_events.append(event)
                            self._zone_alert_cooldowns[pid] = frame_idx
                            logger.info(f"  [Cash] {event}")
                else:
                    # Cash disappeared → enter occlusion grace period
                    profile.state = CashState.CASH_OCCLUDED
                    profile.frames_without_cash = 1

            elif profile.state == CashState.CASH_OCCLUDED:
                if has_cash_now:
                    # Cash came back during grace period → back to confirmed
                    profile.state = CashState.CASH_CONFIRMED
                    profile.frames_without_cash = 0
                    profile.last_cash_confidence = avg_conf
                    if pid in assigned:
                        profile.last_cash_bbox = assigned[pid][0].bbox
                else:
                    profile.frames_without_cash += 1

                    # Grace period expired → decide what happened
                    if profile.frames_without_cash >= self.occlusion_grace_frames:
                        event = self._resolve_cash_gone(
                            pid, profile, person_tracks, current_holders,
                            roles, zone_name, zone_type,
                            current_time, frame_idx,
                        )
                        if event:
                            frame_events.append(event)
                            if event.event_type != CashEventType.NEUTRAL:
                                logger.info(f"  [Cash] {event}")

                        # Reset to NO_CASH
                        profile.state = CashState.NO_CASH
                        profile.frames_with_cash = 0
                        profile.frames_without_cash = 0
                        profile.suspicious_confirm_count = 0
                        profile.last_cash_bbox = None

            elif profile.state == CashState.SUSPICIOUS:
                # Requires confirmation frames before firing POCKET
                profile.suspicious_confirm_count += 1

                if has_cash_now:
                    # False alarm — cash came back
                    profile.state = CashState.CASH_CONFIRMED
                    profile.suspicious_confirm_count = 0
                    profile.frames_without_cash = 0
                elif profile.suspicious_confirm_count >= self.suspicious_confirm_count:
                    # Confirmed suspicious → fire POCKET alert
                    event = CashEvent(
                        event_type=CashEventType.CASH_POCKET,
                        person_id=pid,
                        timestamp=current_time,
                        frame_idx=frame_idx,
                        zone=zone_name,
                        confidence=profile.last_cash_confidence * 0.8,
                        bbox_snapshot=cash_bbox_str,
                    )
                    frame_events.append(event)
                    logger.info(f"  [Cash] {event}")

                    # Reset
                    profile.state = CashState.NO_CASH
                    profile.frames_with_cash = 0
                    profile.frames_without_cash = 0
                    profile.suspicious_confirm_count = 0
                    profile.last_cash_bbox = None

        # Update previous holders for next frame's handover detection
        self._prev_holders = current_holders.copy()

        # Accumulate events
        self._events.extend(frame_events)

        # Periodic stale profile cleanup
        if frame_idx % 300 == 0 and frame_idx > 0:
            self._cleanup_stale_profiles(frame_idx)

        return frame_events

    # ── Behavioral Decision Engine ─────────────────────────────────────

    def _resolve_cash_gone(
        self,
        pid: int,
        profile: CashProfile,
        person_tracks: dict,
        current_holders: Set[int],
        roles: Dict[int, str],
        zone_name: str,
        zone_type: Optional[str],
        current_time: float,
        frame_idx: int,
    ) -> Optional[CashEvent]:
        """
        Decide what happened when cash disappears from a person.

        Decision priority:
          1. Handover → another person just gained cash
          2. Zone-based deposit → person is in a safe zone (when zones exist)
          3. Behavioral deposit → person is near a Cashier or is stationary
          4. Suspicious → person is moving away (enters SUSPICIOUS state)
          5. NEUTRAL → default, no alert

        Returns a CashEvent, or None.
        """
        base_conf = profile.last_cash_confidence

        # 1. HANDOVER: another person just gained cash
        new_holders = current_holders - self._prev_holders
        for new_pid in new_holders:
            if new_pid != pid:
                return CashEvent(
                    event_type=CashEventType.CASH_HANDOVER,
                    person_id=pid,
                    timestamp=current_time,
                    frame_idx=frame_idx,
                    zone=zone_name,
                    confidence=base_conf,
                    partner_id=new_pid,
                )

        # 2. ZONE-BASED DEPOSIT: person is in a safe cash zone
        if zone_type and zone_type in SAFE_CASH_ZONES:
            return CashEvent(
                event_type=CashEventType.CASH_DEPOSIT,
                person_id=pid,
                timestamp=current_time,
                frame_idx=frame_idx,
                zone=zone_name,
                confidence=base_conf,
            )

        # 3. BEHAVIORAL DEPOSIT: near a Cashier-role person → likely deposited
        if roles.get(pid) == "Customer":
            for other_pid, role in roles.items():
                if role == "Cashier" and other_pid != pid:
                    if self._is_near(pid, other_pid, person_tracks):
                        return CashEvent(
                            event_type=CashEventType.CASH_DEPOSIT,
                            person_id=pid,
                            timestamp=current_time,
                            frame_idx=frame_idx,
                            zone=f"near_cashier_{other_pid}",
                            confidence=base_conf * 0.9,
                        )

        # 4. BEHAVIORAL DEPOSIT: person is stationary → probably put it down
        if self._is_stationary(pid):
            return CashEvent(
                event_type=CashEventType.CASH_DEPOSIT,
                person_id=pid,
                timestamp=current_time,
                frame_idx=frame_idx,
                zone=zone_name,
                confidence=base_conf * 0.7,
            )

        # 5. DEFAULT: Neutral — no alert
        return CashEvent(
            event_type=CashEventType.NEUTRAL,
            person_id=pid,
            timestamp=current_time,
            frame_idx=frame_idx,
            zone=zone_name,
            confidence=base_conf * 0.3,
        )

    # ── Helpers ────────────────────────────────────────────────────────

    def _is_near(self, pid_a: int, pid_b: int, person_tracks: dict) -> bool:
        """Check if two persons are within proximity_threshold_px of each other."""
        bbox_a = person_tracks.get(pid_a, {}).get("bbox")
        bbox_b = person_tracks.get(pid_b, {}).get("bbox")
        if not bbox_a or not bbox_b:
            return False

        cx_a = (bbox_a[0] + bbox_a[2]) / 2
        cy_a = (bbox_a[1] + bbox_a[3]) / 2
        cx_b = (bbox_b[0] + bbox_b[2]) / 2
        cy_b = (bbox_b[1] + bbox_b[3]) / 2

        dist = ((cx_a - cx_b) ** 2 + (cy_a - cy_b) ** 2) ** 0.5
        return dist <= self.proximity_threshold_px

    def _is_stationary(self, pid: int) -> bool:
        """Check if a person has been stationary (low position variance)."""
        profile = self._profiles.get(pid)
        if not profile or len(profile.positions) < 10:
            return False

        positions = list(profile.positions)
        xs = [p[0] for p in positions[-30:]]  # Last 30 frames (~1.2s)
        ys = [p[1] for p in positions[-30:]]

        if len(xs) < 10:
            return False

        x_range = max(xs) - min(xs)
        y_range = max(ys) - min(ys)

        return x_range < self.stationary_threshold_px and y_range < self.stationary_threshold_px

    def _cleanup_stale_profiles(self, current_frame: int):
        """Remove profiles that haven't been seen recently."""
        stale = [
            pid for pid, p in self._profiles.items()
            if current_frame - p.last_seen_frame > self.stale_profile_frames
        ]
        for pid in stale:
            del self._profiles[pid]
            self._zone_alert_cooldowns.pop(pid, None)

        if stale:
            logger.debug(f"  [Cash] Cleaned {len(stale)} stale profiles")

    # ── Public API ─────────────────────────────────────────────────────

    def get_all_events(self):
        """Return all accumulated cash events."""
        return self._events

    def get_active_cash_holders(self):
        """Return person IDs currently holding cash."""
        return [
            pid for pid, profile in self._profiles.items()
            if profile.state in (CashState.CASH_CONFIRMED, CashState.CASH_OCCLUDED)
        ]

    def get_person_cash_state(self, person_id):
        """Get cash state for a specific person."""
        if person_id in self._profiles:
            return self._profiles[person_id].state.value
        return CashState.NO_CASH.value

    def get_summary(self):
        """Get a summary dict for debugging/logging."""
        return {
            "total_events": len(self._events),
            "active_holders": len(self.get_active_cash_holders()),
            "active_profiles": len(self._profiles),
            "events_by_type": {
                etype.value: sum(1 for e in self._events if e.event_type == etype)
                for etype in CashEventType
                if etype != CashEventType.NEUTRAL  # Don't clutter summary with neutrals
            },
        }
