"""
Replaces tools/lane_selector.py.

Changes:
  - Video path is a CLI argument (was hardcoded to video1.mp4)
  - Supports multiple named zones
  - Auto-saves to configs/parking_spaces.py on ESC (original only printed)
  - Press L to define the ENTRY_LINE with 2 clicks

Usage:
    python tools/space_annotator.py --video data/videos/video1.mp4

Controls:
    Left-click  : add zone corner
    ENTER       : finish zone (prompts for name)
    R           : clear current zone
    L           : line mode — click 2 points for ENTRY_LINE
    ESC         : save and exit
"""

import sys
import os
import argparse
import cv2
import numpy as np

current_points = []
saved_zones    = {}
entry_line     = None
mode           = "zone"


def mouse_callback(event, x, y, flags, param):
    global current_points, entry_line, mode

    if event != cv2.EVENT_LBUTTONDOWN:
        return

    current_points.append((x, y))
    print(f"  Point {len(current_points)}: ({x}, {y})")

    if mode == "line" and len(current_points) == 2:
        entry_line = (
            current_points[0][0], current_points[0][1],
            current_points[1][0], current_points[1][1],
        )
        print(f"  Entry line set: {entry_line}")
        current_points.clear()
        mode = "zone"


def save_to_config(zones, line):
    config_path = os.path.join(
        os.path.dirname(__file__), "..", "configs", "parking_spaces.py"
    )
    with open(config_path, "w") as f:
        f.write("# auto-generated by tools/space_annotator.py\n\n")
        f.write("PARKING_SPACES = {\n")
        for name, poly in zones.items():
            f.write(f'    "{name}": {poly},\n')
        f.write("}\n\n")
        f.write(f"ENTRY_LINE = {line}\n")
    print(f"\nSaved {len(zones)} zone(s) to {os.path.abspath(config_path)}")


def main():
    global current_points, saved_zones, entry_line, mode

    parser = argparse.ArgumentParser()
    parser.add_argument("--video", required=True)
    args = parser.parse_args()

    cap = cv2.VideoCapture(args.video)
    ret, frame = cap.read()
    cap.release()

    if not ret:
        print("Could not read frame"); sys.exit(1)

    cv2.namedWindow("Space Annotator")
    cv2.setMouseCallback("Space Annotator", mouse_callback)

    print("Left-click=add point | ENTER=finish zone | R=reset | L=line mode | ESC=save+exit\n")

    while True:
        display = frame.copy()

        for name, poly in saved_zones.items():
            pts = np.array(poly, dtype=np.int32)
            cv2.polylines(display, [pts], True, (0, 255, 0), 2)
            cx = sum(p[0] for p in poly) // len(poly)
            cy = sum(p[1] for p in poly) // len(poly)
            cv2.putText(display, name, (cx, cy),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

        for p in current_points:
            cv2.circle(display, p, 5, (0, 0, 255), -1)

        if entry_line:
            cv2.line(display,
                     (entry_line[0], entry_line[1]),
                     (entry_line[2], entry_line[3]),
                     (0, 165, 255), 2)

        cv2.putText(display, f"Mode: {mode.upper()}", (10, 25),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 0), 2)

        cv2.imshow("Space Annotator", display)
        key = cv2.waitKey(1) & 0xFF

        if key == 27:    # ESC
            break
        elif key == 13:  # ENTER
            if len(current_points) >= 3:
                name = input(f"  Zone name [{len(saved_zones)+1}]: ").strip() \
                       or f"zone_{len(saved_zones)+1}"
                saved_zones[name] = current_points.copy()
                current_points.clear()
                print(f"  Saved zone '{name}'")
        elif key == ord('r'):
            current_points.clear()
        elif key == ord('l'):
            mode = "line"
            current_points.clear()
            print("  Line mode: click 2 points for ENTRY_LINE")

    cv2.destroyAllWindows()

    if saved_zones or entry_line:
        save_to_config(saved_zones, entry_line)


if __name__ == "__main__":
    main()
